### ISSUE TITLE
Erroneous warning output if file is not in dest directory

### ISSUE THREAD

**Issue by dpolivy** [ktmud/grunt-hashmap#8]
I'm on Windows, which uses `\` as the path separator, however for consistency I use `/` in my `Gruntfile` when specifying paths (which works just fine).

However, when using `grunt-hashmap` with a `dest` directory, I'm getting an erroneous warning from this line of code:

https://github.com/ktmud/grunt-hashmap/blob/master/tasks/hashmap.js#L145

Essentially, the `indexOf` returns `-1` because the path separators are different from the dest spec and the actual file. An easy fix should be to just pass `dest` to [`path.normalize`](https://nodejs.org/api/path.html#path_path_normalize_path), but I haven't tested it myself.

**Comment by ktmud** [comment]
I don't have Windows at hand to test. Do you mind fixing it and opening a pull request if you have time?

**Comment by dpolivy** [comment]
PR submitted. When I just ran `grunt test` the problem was quite visible on my Windows machine. After the fix, the tests correctly run without the warning output (hence I didn't add any new tests).
